# Generated by Django 5.0.8 on 2024-08-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Django',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('beskriv', models.TextField()),
                ('link_app', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True)),
                ('login', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('beskriv', models.TextField()),
                ('link_app', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True)),
                ('login', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
