# Generated by Django 5.0.8 on 2025-04-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_apps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="small",
            name="foto",
            field=models.ImageField(blank=True, upload_to="staticfiles/images/"),
        ),
    ]
